-- Phase 01 (F005/F006): seed reference data -- 13 hashtags (verbatim,
-- clarifications.md Session 2026-08-31) and the 50 approved departments
-- (spec/department-seed-candidate.md, approved verbatim at the blueprint
-- checkpoint including 'PAO - PAO' and 'CEVEC'). special_days and
-- secret_box_gift stay empty -- admin-managed, no seed rows this round.
-- Rollback: this migration's tables are dropped by migration 1's rollback
-- (cascade); no separate inverse needed.
insert into public.hashtag (name) values
  ('Toàn diện'),
  ('Giỏi chuyên môn'),
  ('Hiệu suất cao'),
  ('Truyền cảm hứng'),
  ('Cống hiến'),
  ('Aim High'),
  ('Be Agile'),
  ('Wasshoi'),
  ('Hướng mục tiêu'),
  ('Hướng khách hàng'),
  ('Chuẩn quy trình'),
  ('Giải pháp sáng tạo'),
  ('Quản lý xuất sắc')
on conflict (name) do nothing;

insert into public.department (name) values
  ('CTO'),
  ('SPD'),
  ('FCOV'),
  ('CEVC1'),
  ('CEVC2'),
  ('STVC - R&D'),
  ('CEVC2 - CySS'),
  ('FCOV - LRM'),
  ('CEVC2 - System'),
  ('OPDC - HRF'),
  ('CEVC1 - DSV - UI/UX 1'),
  ('CEVC1 - DSV'),
  ('CEVEC'),
  ('OPDC - HRD - C&C'),
  ('STVC'),
  ('FCOV - F&A'),
  ('CEVC1 - DSV - UI/UX 2'),
  ('CEVC1 - AIE'),
  ('OPDC - HRF - C&B'),
  ('FCOV - GA'),
  ('FCOV - ISO'),
  ('STVC - EE'),
  ('GEU - HUST'),
  ('CEVEC - SAPD'),
  ('OPDC - HRF - OD'),
  ('CEVEC - GSD'),
  ('GEU - TM'),
  ('STVC - R&D - DTR'),
  ('STVC - R&D - DPS'),
  ('CEVC3'),
  ('STVC - R&D - AIR'),
  ('CEVC4'),
  ('PAO'),
  ('GEU'),
  ('GEU - DUT'),
  ('OPDC - HRD - L&D'),
  ('OPDC - HRD - TI'),
  ('OPDC - HRF - TA'),
  ('GEU - UET'),
  ('STVC - R&D - SDX'),
  ('OPDC - HRD - HRBP'),
  ('PAO - PEC'),
  ('IAV'),
  ('STVC - Infra'),
  ('CPV - CGP'),
  ('GEU - UIT'),
  ('OPDC - HRD'),
  ('BDV'),
  ('CPV'),
  ('PAO - PAO')
on conflict (name) do nothing;
